"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Artur Rychlewicz"
email = "8393226+artuross@users.noreply.github.com"

[ui]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
